# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://manks.org
title: The Manks
email: recruiting@manks.org
author: Cameron Bernhardt
description: > 
  Manks is an exclusive social organization with chapters across the globe. 
  Our members are top tier students and new grads interested or already working 
  in STEM fields.
copyright: 'Copyright &copy; 2019 The Manks. All Rights Reserved.'


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    icon: github
    url: https://github.com/TheManks/
  - title: apply
    icon: check
    url: https://forms.gle/bRWLvGCEx7BC9j6s9
  - title: contact
    icon: envelope
    url: mailto:info@manks.org
